### ISSUE TITLE
Netbox 2.9.x giving 403 after saml implementation

### ISSUE THREAD

**Issue by elnoxgdl** [jeremyschulman/netbox-plugin-auth-saml2#13]
Hi,

I would like to mention something here, after mostly a successful implementation for netbox 2.9.x I'm facing a problem where the reverse proxy is having issues  trying to access /api/plugins/sso/acs/ its now giving a 403 error I understand the API is behind authentication but I was wondering if there is a workaround for this?

**Comment by jeremyschulman** [comment]
Hi @elnoxgdl, I have not attempted to test the plugin with 2.9 myself, so I do not have any direct insights.  I am hoping another user of this plugin has some information to share with you.

**Comment by jeremyschulman** [comment]
Just uploaded recent contributions that should resolve these issues:
https://pypi.org/project/netbox-plugin-auth-saml2/2.0/

Please confirm when you can, thank you!

**Comment by jeremyschulman** [comment]
@elnoxgdl - I am planning to close this issue next week unless I hear otherwise from you.  Hope all is well.

**Comment by kilker12** [comment]
I am having this same issue on v2.1. What specifically was the fix for this?

**Comment by jeremyschulman** [comment]
closed due to lack of activity.
