### ISSUE TITLE
Netbox upgrade plugin validation error

### ISSUE THREAD

**Issue by tdrevvatne** [jeremyschulman/netbox-plugin-auth-saml2#17]
Having a netbox installation with this SAML-plugin, it has been possible to upgrade until 2.9.10.
Trying to upgrade to a late netbox relase, beeing 2.9.11 og 2.10.x, there's a plugin validaion error.
This issue is most probably related to this plugin.
More detail and "fix": https://github.com/netbox-community/netbox/discussions/5490
Waiting for a fix......

**Comment by jeremyschulman** [comment]
Just uploaded the recent contributions that should fix this issue:
https://pypi.org/project/netbox-plugin-auth-saml2/2.0/

Please let me know if all goes well.  Thank you!

**Comment by tdrevvatne** [comment]
Thanks - validation was fine - upgrade got through..:)

**Comment by jeremyschulman** [comment]
excellent, thank you.  closing this issue.
