### ISSUE TITLE
The latest palugin causes netbox worker contaner to exit

### ISSUE THREAD

**Issue by barmalej1** [jeremyschulman/netbox-plugin-auth-saml2#20]
I start seeing this entry in logs "netbox-worker_1  | Error 111 connecting to redis:6379. Connection refused." as soon as I enable plugin in v2.10.3. Any ideas what could be causing this?

**Comment by jeremyschulman** [comment]
@barmalej1 - I am not using NB v2.10, so I am not familiar.  Hopefully others might have some thoughts.

**Comment by jeremyschulman** [comment]
@barmalej1 - understood, thank you for the update.
