### ISSUE TITLE
Support for Netbox 2.10

### ISSUE THREAD

**Issue by jeremyschulman** [jeremyschulman/netbox-plugin-auth-saml2#26]
A lot of folks are now using Netbox 2.10 release, but I have not yet upgraded.  I am looking for contributors to make the necessary updates to support this release as well as the previous releases.

**Comment by devon-mar** [comment]
I'm currently running the plugin on NetBox 2.10.5 in Docker without issue.
I'm installing the plugin from the master branch though instead of using the pypi package.

I can share my image if there's interest.

**Comment by jeremyschulman** [comment]
thank you!  I did make the fix and posted v2.3 to pypi.  Closing this issue.
