### ISSUE TITLE
Not for me!!!

### ISSUE THREAD

**Issue by pixelrebel** [jeremyschulman/netbox-plugin-auth-saml2#34]
After setting up everything according to the documentation, after logging in with Okta, I am redirected to `https://netbox.mydomain.net/sso/acs/` where I receive the following error:
```
{"error": "Not for me!!!", "exception": "Exception", "netbox_version": "2.10.8", "python_version": "3.8.5"}
```

I don't see anything in the log other than a line for "Internal Server Error."  Any guidance would be appreciated, thanks!

**Comment by jeremyschulman** [comment]
@pixelrebel - I see you also asked on issue #10.  I too am curious; this exception is generated by the python SAML2 package pysaml2.

**Comment by pixelrebel** [comment]
I was using the wrong backend `django3_saml2_nbplugin.backends.SAML2AttrUserBackend`.  I switched it back to `django.contrib.auth.backends.RemoteUserBackend` and it seems to be working now.
