### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by ignatenkobrain** [jeremyschulman/netbox-plugin-auth-saml2#43]
Hello,

The Apache license requires license text to be present along with source, but I can't find it in this git repository.

Would appreciate if you could add it and make a new release (so that it appears also on pypi.org).

Thank you!

**Comment by jeremyschulman** [comment]
@jeffgdotorg - thank you.  I'll assign this to you.

**Comment by jeffgdotorg** [comment]
@jeremyschulman sorry about the extra PR. I used `curl` to grab the file directly from apache.org and forgot to rename it before committing.
