### ISSUE TITLE
Error: NameError: name 'REMOTE_AUTH_BACKEND' is not defined

### ISSUE THREAD

**Issue by kaon1** [jeremyschulman/netbox-plugin-auth-saml2#47]
Seeing this error on the latest version of Netbox 3.0.X.

I tried pinning `pysaml2                       6.5.0` as mentioned in another thread.

Running python3 version 3.7.12

My REMOTE_AUTH_BACKEND value is defined, not sure why I'm seeing the error.

```
# Remote authentication support
REMOTE_AUTH_ENABLED = True
REMOTE_AUTH_BACKEND = 'utilities.auth_backends.RemoteUserBackend'
REMOTE_AUTH_HEADER = 'HTTP_REMOTE_USER'
REMOTE_AUTH_AUTO_CREATE_USER = True
REMOTE_AUTH_DEFAULT_GROUPS = []
REMOTE_AUTH_DEFAULT_PERMISSIONS = {}
```

**Comment by kaon1** [comment]
Think I figured it out sorry for the noise

**Comment by mp-strachan** [comment]
What was your solution @kaon1? I'm having this same problem and can't seem to resolve it.

**Comment by kaon1** [comment]
```
# Remote authentication support
REMOTE_AUTH_ENABLED = True
REMOTE_AUTH_BACKEND = 'django3_saml2_nbplugin.backends.SAML2CustomAttrUserBackend'
REMOTE_AUTH_AUTO_CREATE_USER = True
REMOTE_AUTH_DEFAULT_GROUPS = []
REMOTE_AUTH_DEFAULT_PERMISSIONS = {}
```

The above config works for me, my original issue had a simple syntax error in the config. Make sure these two plugins are installed in your python env:

```
netbox-plugin-auth-saml2
django3_auth_saml2
```
