### ISSUE TITLE
Future development after Netbox 3.1.0

### ISSUE THREAD

**Issue by MichalMMac** [jeremyschulman/netbox-plugin-auth-saml2#51]
Hey,

Netbox 3.1.0 now [supports](https://github.com/netbox-community/netbox/issues/2328) SSO out of the box via [python-social-auth](https://github.com/python-social-auth). 

Would this affect the future development of `netbox-plugin-auth-saml2` in any way? Do you @jeremyschulman plan to keep developing/maintaining `netbox-plugin-auth-saml2` plugin?

From the configuration point of view I like the `netbox-plugin-auth-saml2` more. Especially because of the user flag and group synchronization.

**Comment by jeremyschulman** [comment]
Hi @MichalMMac - the Netbox 3.1.0 release will not affect the future development of netbox-plugin-auth-saml2 project.  Thank you for your feedback!

**Comment by ryanmerolle** [comment]
I wonder if django's social auth supports flag and group synchronization.  Could be worth inquiring?
