### ISSUE TITLE
Is this even required for 3.1+?

### ISSUE THREAD

**Issue by ryanmerolle** [jeremyschulman/netbox-plugin-auth-saml2#55]
With [django social included in 3.1.0](https://github.com/netbox-community/netbox/releases/tag/v3.1.0), is this project even needed for anything 3.1+?

**Comment by markkuleinio** [comment]
@ryanmerolle Do you have/know a working configuration example for it when using Azure AD?

**Comment by MichalMMac** [comment]
https://github.com/jeremyschulman/netbox-plugin-auth-saml2/issues/51

**Comment by ryanmerolle** [comment]
duplicate as @MichalMMac stated
