### ISSUE TITLE
Netbox 3.2

### ISSUE THREAD

**Issue by chrisho95** [jeremyschulman/netbox-plugin-auth-saml2#56]
Hi,

Does this plugin work on version 3.2 of Netbox ?

I saw that it was written that only versions below were supported. Do we ever know.

"***NOTE: Netbox plugin for SSO, v2.0+, supports Netbox 2.8, 2.9, 2.10, 2.11, 3.0.**"

BR,

Chris.

**Comment by devon-mar** [comment]
Yes, I'm using it with 3.2.

**Comment by chrisho95** [comment]
Ok, Thanks.

BR,

Chris.
