### ISSUE TITLE
A file permission error was detected while processing this request. Common causes include the following

### ISSUE THREAD

**Issue by absmith82** [jeremyschulman/netbox-plugin-auth-saml2#58]
I get this error anytime I use the django3_saml2_nbplugin.backends any plugin.  SAML auth works using Django contrib remote user but does not auto assign groups and flags so obviously the custom backend would be nicer.

I am using the netbox community docker container on kubernetes 

A file permission error was detected while processing this request. Common causes include the following:

Insufficient write permission to the media root - The configured media root is . Ensure that the user NetBox runs as has access to write files to all locations within this path.

The complete exception is provided below:

<class 'PermissionError'>

SAML2 backend SAML2CustomAttrUserBackend missing attribute: emailaddress

Python version: 3.9.5
NetBox version: 3.2.1

**Comment by devon-mar** [comment]
> SAML2 backend SAML2CustomAttrUserBackend missing attribute: emailaddress

Can you check that your IDP is sending the correct attributes?

**Comment by markkuleinio** [comment]
`emailAddress` instead of `emailaddress`?

**Comment by absmith82** [comment]
Thank you, that is what I was missing.

I was trying both the full namespace and attribute, and just the attribute, but I missed the CaMel TyPe for some reason on the list listed in pysaml2.
