### ISSUE TITLE
Error To Early with SALM login

### ISSUE THREAD

**Issue by chrisho95** [jeremyschulman/netbox-plugin-auth-saml2#81]
Hello,

when I try to connect via SSO (saml) to Netbox (version 4.0.3), I get the following error.

I installed the following plugins:

- django3-auth-saml2 (last version)
- netbox-plugin-auth-saml2 (version 3.0)

![image](https://github.com/jeremyschulman/netbox-plugin-auth-saml2/assets/82440344/2437ab6c-4989-47be-8b1f-4635664c01b2)

![image](https://github.com/jeremyschulman/netbox-plugin-auth-saml2/assets/82440344/389dcfb2-a96f-44a2-b380-5b1f7fba1aca)

BR,

Chris

**Comment by markkuleinio** [comment]
Try fixing your time: it shows in the error message that "now" is 6 seconds too early.

**Comment by chrisho95** [comment]
Hi,

Indeed, the time of the VM that hosts Keycloak is ahead of the VM that hosts my Netbox instance. Thanks for your help.

I'll look into this date issue.

Br,

Chris.
